USE Currencies;

INSERT INTO Currencies (currency_name, alpha2,CallingCodes, alpha3, ioc, symbol) VALUES
('Peru','PE','51','PER','PER','PEN'),
('French Polynesia','PF','689','PYF','','XPF'),
('Papua New Guinea','PG','675','PNG','PNG','PGK'),
('Philippines','PH','63','PHL','PHI','PHP'),
('Pakistan','PK','92','PAK','PAK','PKR'),
('Poland','PL','48','POL','POL','PLN'),
('Saint Pierre And Miquelon','PM','508','SPM','','EUR'),
('Pitcairn','PN','872','PCN','','NZD'),
('Puerto Rico','PR','+1 787','+1 939','PRI','PUR'),
('Palestinian Territory','PS','970','PSE','PLE','JOD'),
('Portugal','PT','351','PRT','POR','EUR'),
('Palau','PW','680','PLW','PLW','USD'),
('Paraguay','PY','595','PRY','PAR','PYG'),
('Qatar','QA','974','QAT','QAT','QAR'),
('Reunion','RE','262','REU','','EUR'),
('Romania','RO','40','ROU','ROU','RON'),
('Serbia','RS','381','SRB','SRB','RSD'),
('Russian Federation','RU','7','+7 3','+7 4','+7 8'),
('Rwanda','RW','250','RWA','RWA','RWF'),
('Saudi Arabia','SA','966','SAU','KSA','SAR'),
('Solomon Islands','SB','677','SLB','SOL','SBD'),
('Seychelles','SC','248','SYC','SEY','SCR'),
('Sudan','SD','249','SDN','SUD','SDG'),
('Sweden','SE','46','SWE','SWE','SEK'),
('Singapore','SG','65','SGP','SIN','SGD'),
('Saint Helena','SH','290','SHN','','SHP'),
('Slovenia','SI','386','SVN','SLO','EUR'),
('Svalbard And Jan Mayen','SJ','47','SJM','','NOK'),
('Slovakia','SK','421','SVK','SVK','EUR'),
('Sierra Leone','SL','232','SLE','SLE','SLL'),
('San Marino','SM','378','SMR','SMR','EUR'),
('Senegal','SN','221','SEN','SEN','XOF'),
('Somalia','SO','252','SOM','SOM','SOS'),
('Suriname','SR','597','SUR','SUR','SRD'),
('South Sudan','SS','211','SSD','','SSP'),
('SÃ£o TomÃ© and PrÃ­ncipe','ST','239','STP','STP','STD'),
('USSR','SU','','','','RUB'),
('El Salvador','SV','503','SLV','ESA','USD'),
('Sint Maarten','SX','+1 721','SXM','','ANG'),
('Syrian Arab Republic','SY','963','SYR','SYR','SYP'),
('Swaziland','SZ','268','SWZ','SWZ','SZL'),
('Turks And Caicos Islands','TC','+1 649','TCA','','USD'),
('Tristan de Cunha','TA','290','','','GBP'),
('Chad','TD','235','TCD','CHA','XAF'),
('French Southern Territories','TF','','ATF','','EUR'),
('Togo','TG','228','TGO','TOG','XOF'),
('Thailand','TH','66','THA','THA','THB'),
('Tajikistan','TJ','992','TJK','TJK','TJS'),
('Tokelau','TK','690','TKL','','NZD'),
('East Timor','TL','670','TLS','TLS','USD'),
('Turkmenistan','TM','993','TKM','TKM','TMT'),
('Tunisia','TN','216','TUN','TUN','TND'),
('Tonga','TO','676','TON','TGA','TOP'),
('Turkey','TR','90','TUR','TUR','TRY'),
('Trinidad And Tobago','TT','+1 868','TTO','TRI','TTD'),
('Tuvalu','TV','688','TUV','TUV','AUD'),
('Taiwan',' TW','886','TWN','TPE','TWD'),
('Tanzania','TZ','255','TZA','TAN','TZS'),
('Ukraine','UA','380','UKR','UKR','UAH'),
('Uganda','UG','256','UGA','UGA','UGX');