USE Currencies;

INSERT INTO Currencies (currency_name, alpha2,CallingCodes, alpha3, ioc, symbol) VALUES
('Ascension Island','AC','247','AC2','SHP','USD'),
('Andorra','AD','376','AND','AND','EUR'),
('United Arab Emirates','AE','971','ARE','UAE','AED'),
('Afghanistan','AF','93','AFG','AFG','AFN'),
('Antigua And Barbuda','AG','+1 268','ATG','ANT','XCD'),
('Anguilla','AI','+1 264','AIA','','XCD'),
('Albania','AL','355','ALB','ALB','ALL'),
('Armenia','AM','374','ARM','ARM','AMD'),
('Angola','AO','244','AGO','ANG','AOA'),
('Antarctica','AQ','672','ATA','',''),
('Argentina','AR','54','ARG','ARG','ARS'),
('American Samoa','AS','+1 684','ASM','ASA','USD'),
('Austria','AT','43','AUT','AUT','EUR'),
('Australia','AU','61','AUS','AUS','AUD'),
('Aruba','AW','297','ABW','ARU','AWG'),
('Ã…land Islands','AX','358','ALA','','EUR'),
('Azerbaijan','AZ','994','AZE','AZE','AZN'),
('Bosnia & Herzegovina','BA','387','BIH','BIH','BAM'),
('Barbados','BB','+1 246','BRB','BAR','BBD'),
('Bangladesh','BD','880','BGD','BAN','BDT'),
('Belgium','BE','32','BEL','BEL','EUR'),
('Burkina Faso','BF','226','BFA','BUR','XOF'),
('Bulgaria','BG','359','BGR','BUL','BGN'),
('Bahrain','BH','973','BHR','BRN','BHD'),
('Burundi','BI','257','BDI','BDI','BIF'),
('Benin','BJ','229','BEN','BEN','XOF'),
('Saint BarthÃ©lemy','BL','590','BLM','','EUR'),
('Bermuda','BM','+1 441','BMU','BER','BMD'),
('Brunei Darussalam','BN','673','BRN','BRU','BND'),
('Bolivia','BO','591','BOL','BOL','BOB'),
('Bonaire','BQ','599','BES','','USD'),
('Brazil','BR','55','BRA','BRA','BRL'),
('Bahamas','BS','+1 242','BHS','BAH','BSD'),
('Bhutan','BT','975','BTN','BHU','INR'),
('Bouvet Island','BV','','BVT','','NOK'),
('Botswana','BW','267','BWA','BOT','BWP'),
('Belarus','BY','375','BLR','BLR','BYR'),
('Belize','BZ','501','BLZ','BIZ','BZD'),
('Canada','CA','1','CAN','CAN','CAD'),
('Cocos','CC','61','CCK','','AUD'),
('Democratic Republic Of Congo','CD','243','COD','COD','CDF'),
('Central African ','CF','236','CAF','CAF','XAF'),
('Republic Of Congo','CG','242','COG','CGO','XAF'),
('Switzerland','CH','41','CHE','SUI','CHF'),
('Cote d Ivoire','CI','225','CIV','CIV','XOF'),
('Cook Islands','CK','682','COK','COK','NZD'),
('Chile','CL','56','CHL','CHI','CLP'),
('Cameroon','CM','237','CMR','CMR','XAF'),
('China','CN','86','CHN','CHN','CNY'),
('Colombia','CO','57','COL','COL','COP'),
('Clipperton Island','CP','','','','EUR'),
('Costa Rica','CR','506','CRI','CRC','CRC'),
('Cuba','CU','53','CUB','CUB','CUP'),
('Cabo Verde','CV','238','CPV','CPV','CVE'),
('Curacao','CW','599','CUW','','ANG'),
('Christmas Island','CX','61','CXR','','AUD'),
('Cyprus','CY','357','CYP','CYP','EUR'),
('Czech Republic','CZ','420','CZE','CZE','CZK'),
('Germany','DE','49','DEU','GER','EUR'),
('Diego Garcia','DG',''   ,''   ,''   ,'USD');
