USE Currencies;

INSERT INTO Currencies (currency_name, alpha2,CallingCodes, alpha3, ioc, symbol) VALUES
('Ascension Island','AC','247','AC2','SHP','USD'),
('Andorra','AD','376','AND','AND','EUR'),
('United Arab Emirates','AE','971','ARE','UAE','AED'),
('Afghanistan','AF','93','AFG','AFG','AFN'),
('Antigua And Barbuda','AG','+1 268','ATG','ANT','XCD'),
('Anguilla','AI','+1 264','AIA','','XCD'),
('Albania','AL','355','ALB','ALB','ALL'),
('Armenia','AM','374','ARM','ARM','AMD'),
('Angola','AO','244','AGO','ANG','AOA'),
('Antarctica','AQ','672','ATA','',''),
('Argentina','AR','54','ARG','ARG','ARS'),
('American Samoa','AS','+1 684','ASM','ASA','USD'),
('Austria','AT','43','AUT','AUT','EUR'),
('Australia','AU','61','AUS','AUS','AUD'),
('Aruba','AW','297','ABW','ARU','AWG'),
('Ã…land Islands','AX','358','ALA','','EUR'),
('Azerbaijan','AZ','994','AZE','AZE','AZN'),
('Bosnia & Herzegovina','BA','387','BIH','BIH','BAM'),
('Barbados','BB','+1 246','BRB','BAR','BBD'),
('Bangladesh','BD','880','BGD','BAN','BDT'),
('Belgium','BE','32','BEL','BEL','EUR'),
('Burkina Faso','BF','226','BFA','BUR','XOF'),
('Bulgaria','BG','359','BGR','BUL','BGN'),
('Bahrain','BH','973','BHR','BRN','BHD'),
('Burundi','BI','257','BDI','BDI','BIF'),
('Benin','BJ','229','BEN','BEN','XOF'),
('Saint BarthÃ©lemy','BL','590','BLM','','EUR'),
('Bermuda','BM','+1 441','BMU','BER','BMD'),
('Brunei Darussalam','BN','673','BRN','BRU','BND'),
('Bolivia','BO','591','BOL','BOL','BOB'),
('Bonaire','BQ','599','BES','','USD'),
('Brazil','BR','55','BRA','BRA','BRL'),
('Bahamas','BS','+1 242','BHS','BAH','BSD'),
('Bhutan','BT','975','BTN','BHU','INR'),
('Bouvet Island','BV','','BVT','','NOK'),
('Botswana','BW','267','BWA','BOT','BWP'),
('Belarus','BY','375','BLR','BLR','BYR'),
('Belize','BZ','501','BLZ','BIZ','BZD'),
('Canada','CA','1','CAN','CAN','CAD'),
('Cocos','CC','61','CCK','','AUD'),
('Democratic Republic Of Congo','CD','243','COD','COD','CDF'),
('Central African ','CF','236','CAF','CAF','XAF'),
('Republic Of Congo','CG','242','COG','CGO','XAF'),
('Switzerland','CH','41','CHE','SUI','CHF'),
('Cote d Ivoire','CI','225','CIV','CIV','XOF'),
('Cook Islands','CK','682','COK','COK','NZD'),
('Chile','CL','56','CHL','CHI','CLP'),
('Cameroon','CM','237','CMR','CMR','XAF'),
('China','CN','86','CHN','CHN','CNY'),
('Colombia','CO','57','COL','COL','COP'),
('Clipperton Island','CP','','','','EUR'),
('Costa Rica','CR','506','CRI','CRC','CRC'),
('Cuba','CU','53','CUB','CUB','CUP'),
('Cabo Verde','CV','238','CPV','CPV','CVE'),
('Curacao','CW','599','CUW','','ANG'),
('Christmas Island','CX','61','CXR','','AUD'),
('Cyprus','CY','357','CYP','CYP','EUR'),
('Czech Republic','CZ','420','CZE','CZE','CZK'),
('Germany','DE','49','DEU','GER','EUR'),
('Diego Garcia','DG',''   ,''   ,''   ,'USD'),
('Djibouti',    'DJ','253','DJI','DJI','DJF'),
('Denmark','DK','45','DNK','DEN','DKK'),
('Dominica','DM','+1 767','DMA','DMA','XCD'),
('Dominican Republic','DO','+1 809','+1 829','+1 849','DOM'),
('Algeria','DZ','213','DZA','ALG','DZD'),
('Ceuta',' Mulilla','EA','','',''),
('Ecuador','EC','593','ECU','ECU','USD'),
('Estonia','EE','372','EST','EST','EUR'),
('Egypt','EG','20','EGY','EGY','EGP'),
('Western Sahara','EH','212','ESH','','MAD'),
('Eritrea','ER','291','ERI','ERI','ERN'),
('Spain','ES','34','ESP','ESP','EUR'),
('Ethiopia','ET','251','ETH','ETH','ETB'),
('European Union','EU','388','','','EUR'),
('Finland','FI','358','FIN','FIN','EUR'),
('Fiji','FJ','679','FJI','FIJ','FJD'),
('Falkland Islands','FK','500','FLK','','FKP'),
('Micronesia','FM','691','FSM','','USD'),
('Faroe Islands','FO','298','FRO','FAI','DKK'),
('France','FR','33','FRA','FRA','EUR'),
('France','FX','241','','','EUR'),
('Gabon','GA','241','GAB','GAB','XAF'),
('United Kingdom','GB','44','GBR','GBR','GBP'),
('Grenada','GD','473','GRD','GRN','XCD'),
('Georgia','GE','995','GEO','GEO','GEL'),
('French Guiana','GF','594','GUF','','EUR'),
('Guernsey','GG','44','GGY','GCI','GBP'),
('Ghana','GH','233','GHA','GHA','GHS'),
('Gibraltar','GI','350','GIB','','GIP'),
('Greenland','GL','299','GRL','','DKK'),
('Gambia','GM','220','GMB','GAM','GMD'),
('Guinea','GN','224','GIN','GUI','GNF'),
('Guadeloupe','GP','590','GLP','','EUR'),
('Equatorial Guinea','GQ','240','GNQ','GEQ','XAF'),
('Greece','GR','30','GRC','GRE','EUR'),
('South Georgia And The South Sandwich Islands','GS','','SGS','','GBP'),
('Guatemala','GT','502','GTM','GUA','GTQ'),
('Guam','GU','+1 671','GUM','GUM','USD'),
('Guinea-bissau','GW','245','GNB','GBS','XOF'),
('Guyana','GY','592','GUY','GUY','GYD'),
('Hong Kong','HK','852','HKG','HKG','HKD'),
('Heard Island And McDonald Islands','HM','','HMD','','AUD'),
('Honduras','HN','504','HND','HON','HNL'),
('Croatia','HR','385','HRV','CRO','HRK'),
('Haiti','HT','509','HTI','HAI','HTG'),
('Hungary','HU','36','HUN','HUN','HUF'),
('Canary Islands','IC','','','','EUR'),
('Indonesia','ID','62','IDN','INA','IDR'),
('Ireland','IE','353','IRL','IRL','EUR'),
('Israel','IL','972','ISR','ISR','ILS'),
('Isle Of Man','IM','44','IMN','','GBP'),
('India','IN','91','IND','IND','INR'),
('British Indian','IO','246','IOT','','USD'),
('Iraq','IQ','964','IRQ','IRQ','IQD'),
('Iran','IR','98','IRN','IRI','IRR'),
('Iceland','IS','354','ISL','ISL','ISK'),
('Italy','IT','39','ITA','ITA','EUR'),
('Jersey','JE','44','JEY','JCI','GBP'),
('Jamaica','JM','+1 876','JAM','JAM','JMD'),
('Jordan','JO','962','JOR','JOR','JOD'),
('Japan','JP','81','JPN','JPN','JPY'),
('Kenya','KE','254','KEN','KEN','KES'),
('Kyrgyzstan','KG','996','KGZ','KGZ','KGS'),
('Cambodia','KH','855','KHM','CAM','KHR'),
('Kiribati','KI','686','KIR','KIR','AUD'),
('Comoros','KM','269','COM','COM','KMF'),
('Saint Kitts And Nevis','KN','+1 869','KNA','SKN','XCD'),
('Korea North','KP','850','PRK','PRK','KPW'),
('Korea South','KR','82','KOR','KOR','KRW'),
('Kuwait','KW','965','KWT','KUW','KWD'),
('Cayman Islands','KY','+1 345','CYM','CAY','KYD'),
('Kazakhstan','KZ','7','+7 6','+7 7','KAZ'),
('Lao Peoples Democratic Republic','LA','856','LAO','LAO','LAK'),
('Lebanon','LB','961','LBN','LIB','LBP'),
('Saint Lucia','LC','+1 758','LCA','LCA','XCD'),
('Liechtenstein','LI','423','LIE','LIE','CHF'),
('Sri Lanka','LK','94','LKA','SRI','LKR'),
('Liberia','LR','231','LBR','LBR','LRD'),
('Lesotho','LS','266','LSO','LES','LSL'),
('Lithuania','LT','370','LTU','LTU','EUR'),
('Luxembourg','LU','352','LUX','LUX','EUR'),
('Latvia','LV','371','LVA','LAT','EUR'),
('Libya','LY','218','LBY','LBA','LYD'),
('Morocco','MA','212','MAR','MAR','MAD'),
('Monaco','MC','377','MCO','MON','EUR'),
('Moldova','MD','373','MDA','MDA','MDL'),
('Montenegro','ME','382','MNE','MNE','EUR'),
('Saint Martin','MF','590','MAF','','EUR'),
('Madagascar','MG','261','MDG','MAD','MGA'),
('Marshall Islands','MH','692','MHL','MHL','USD'),
('Macedonia','MK','389','MKD','MKD','MKD'),
('Mali','ML','223','MLI','MLI','XOF'),
('Myanmar','MM','95','MMR','MYA','MMK'),
('Mongolia','MN','976','MNG','MGL','MNT'),
('Macao','MO','853','MAC','MAC','MOP'),
('Northern Mariana Islands','MP','+1 670','MNP','','USD'),
('Martinique','MQ','596','MTQ','','EUR'),
('Mauritania','MR','222','MRT','MTN','MRO'),
('Montserrat','MS','+1 664','MSR','','XCD'),
('Malta','MT','356','MLT','MLT','EUR'),
('Mauritius','MU','230','MUS','MRI','MUR'),
('Maldives','MV','960','MDV','MDV','MVR'),
('Malawi','MW','265','MWI','MAW','MWK'),
('Mexico','MX','52','MEX','MEX','MXN'),
('Malaysia','MY','60','MYS','MAS','MYR'),
('Mozambique','MZ','258','MOZ','MOZ','MZN'),
('Namibia','NA','264','NAM','NAM','NAD'),
('New Caledonia','NC','687','NCL','','XPF'),
('Niger','NE','227','NER','NIG','XOF'),
('Norfolk Island','NF','672','NFK','','AUD'),
('Nigeria','NG','234','NGA','NGR','NGN'),
('Nicaragua','NI','505','NIC','NCA','NIO'),
('Netherlands','NL','31','NLD','NED','EUR'),
('Norway','NO','47','NOR','NOR','NOK'),
('Nepal','NP','977','NPL','NEP','NPR'),
('Nauru','NR','674','NRU','NRU','AUD'),
('Niue','NU','683','NIU','','NZD'),
('New Zealand','NZ','64','NZL','NZL','NZD'),
('Oman','OM','968','OMN','OMA','OMR'),
('Panama','PA','507','PAN','PAN','PAB'),
('Peru','PE','51','PER','PER','PEN'),
('French Polynesia','PF','689','PYF','','XPF'),
('Papua New Guinea','PG','675','PNG','PNG','PGK'),
('Philippines','PH','63','PHL','PHI','PHP'),
('Pakistan','PK','92','PAK','PAK','PKR'),
('Poland','PL','48','POL','POL','PLN'),
('Saint Pierre And Miquelon','PM','508','SPM','','EUR'),
('Pitcairn','PN','872','PCN','','NZD'),
('Puerto Rico','PR','+1 787','+1 939','PRI','PUR'),
('Palestinian Territory','PS','970','PSE','PLE','JOD'),
('Portugal','PT','351','PRT','POR','EUR'),
('Palau','PW','680','PLW','PLW','USD'),
('Paraguay','PY','595','PRY','PAR','PYG'),
('Qatar','QA','974','QAT','QAT','QAR'),
('Reunion','RE','262','REU','','EUR'),
('Romania','RO','40','ROU','ROU','RON'),
('Serbia','RS','381','SRB','SRB','RSD'),
('Russian Federation','RU','7','+7 3','+7 4','+7 8'),
('Rwanda','RW','250','RWA','RWA','RWF'),
('Saudi Arabia','SA','966','SAU','KSA','SAR'),
('Solomon Islands','SB','677','SLB','SOL','SBD'),
('Seychelles','SC','248','SYC','SEY','SCR'),
('Sudan','SD','249','SDN','SUD','SDG'),
('Sweden','SE','46','SWE','SWE','SEK'),
('Singapore','SG','65','SGP','SIN','SGD'),
('Saint Helena','SH','290','SHN','','SHP'),
('Slovenia','SI','386','SVN','SLO','EUR'),
('Svalbard And Jan Mayen','SJ','47','SJM','','NOK'),
('Slovakia','SK','421','SVK','SVK','EUR'),
('Sierra Leone','SL','232','SLE','SLE','SLL'),
('San Marino','SM','378','SMR','SMR','EUR'),
('Senegal','SN','221','SEN','SEN','XOF'),
('Somalia','SO','252','SOM','SOM','SOS'),
('Suriname','SR','597','SUR','SUR','SRD'),
('South Sudan','SS','211','SSD','','SSP'),
('SÃ£o TomÃ© and PrÃ­ncipe','ST','239','STP','STP','STD'),
('USSR','SU','','','','RUB'),
('El Salvador','SV','503','SLV','ESA','USD'),
('Sint Maarten','SX','+1 721','SXM','','ANG'),
('Syrian Arab Republic','SY','963','SYR','SYR','SYP'),
('Swaziland','SZ','268','SWZ','SWZ','SZL'),
('Turks And Caicos Islands','TC','+1 649','TCA','','USD'),
('Tristan de Cunha','TA','290','','','GBP'),
('Chad','TD','235','TCD','CHA','XAF'),
('French Southern Territories','TF','','ATF','','EUR'),
('Togo','TG','228','TGO','TOG','XOF'),
('Thailand','TH','66','THA','THA','THB'),
('Tajikistan','TJ','992','TJK','TJK','TJS'),
('Tokelau','TK','690','TKL','','NZD'),
('East Timor','TL','670','TLS','TLS','USD'),
('Turkmenistan','TM','993','TKM','TKM','TMT'),
('Tunisia','TN','216','TUN','TUN','TND'),
('Tonga','TO','676','TON','TGA','TOP'),
('Turkey','TR','90','TUR','TUR','TRY'),
('Trinidad And Tobago','TT','+1 868','TTO','TRI','TTD'),
('Tuvalu','TV','688','TUV','TUV','AUD'),
('Taiwan',' TW','886','TWN','TPE','TWD'),
('Tanzania','TZ','255','TZA','TAN','TZS'),
('Ukraine','UA','380','UKR','UKR','UAH'),
('Uganda','UG','256','UGA','UGA','UGX'),
('US Minor Outlying','UM','1','UMI','','USD'),
('United Kingdom','UK','','','','GBP'),
('United States','US','1','USA','USA','USD'),
('Uruguay','UY','598','URY','URU','UYU'),
('Uzbekistan','UZ','998','UZB','UZB','UZS'),
('Vatican City','VA','379','39','VAT',''),
('St Vincent & Grenadines','VC','+1 784','VCT','VIN','XCD'),
('Venezuela','VE','58','VEN','VEN','VEF'),
('Virgin (British)','VG','+1 284','VGB','ISV','USD'),
('Virgin (US)','VI','+1 340','VIR','ISV','USD'),
('Viet Nam','VN','84','VNM','VIE','VND'),
('Vanuatu','VU','678','VUT','VAN','VUV'),
('Wallis And Futuna','WF','681','WLF','','XPF'),
('Samoa','WS','685','WSM','SAM','WST'),
('Yemen','YE','967','YEM','YEM','YER'),
('Mayotte','YT','262','MYT','','EUR'),
('South Africa','ZA','27','ZAF','RSA','ZAR'),
('Zambia','ZM','260','ZMB','ZAM','ZMW'),
('Zimbabwe','ZW','263','ZWE','ZIM','USD');