USE Currencies;

INSERT INTO Currencies (currency_name, alpha2,CallingCodes, alpha3, ioc, symbol) VALUES
('Djibouti','DJ','253','DJI','DJI','DJF'),
('Denmark','DK','45','DNK','DEN','DKK'),
('Dominica','DM','+1 767','DMA','DMA','XCD'),
('Dominican Republic','DO','+1 809','+1 829','+1 849','DOM'),
('Algeria','DZ','213','DZA','ALG','DZD'),
('Ceuta',' Mulilla','EA','','',''),
('Ecuador','EC','593','ECU','ECU','USD'),
('Estonia','EE','372','EST','EST','EUR'),
('Egypt','EG','20','EGY','EGY','EGP'),
('Western Sahara','EH','212','ESH','','MAD'),
('Eritrea','ER','291','ERI','ERI','ERN'),
('Spain','ES','34','ESP','ESP','EUR'),
('Ethiopia','ET','251','ETH','ETH','ETB'),
('European Union','EU','388','','','EUR'),
('Finland','FI','358','FIN','FIN','EUR'),
('Fiji','FJ','679','FJI','FIJ','FJD'),
('Falkland Islands','FK','500','FLK','','FKP'),
('Micronesia','FM','691','FSM','','USD'),
('Faroe Islands','FO','298','FRO','FAI','DKK'),
('France','FR','33','FRA','FRA','EUR'),
('France','FX','241','','','EUR'),
('Gabon','GA','241','GAB','GAB','XAF'),
('United Kingdom','GB','44','GBR','GBR','GBP'),
('Grenada','GD','473','GRD','GRN','XCD'),
('Georgia','GE','995','GEO','GEO','GEL'),
('French Guiana','GF','594','GUF','','EUR'),
('Guernsey','GG','44','GGY','GCI','GBP'),
('Ghana','GH','233','GHA','GHA','GHS'),
('Gibraltar','GI','350','GIB','','GIP'),
('Greenland','GL','299','GRL','','DKK'),
('Gambia','GM','220','GMB','GAM','GMD'),
('Guinea','GN','224','GIN','GUI','GNF'),
('Guadeloupe','GP','590','GLP','','EUR'),
('Equatorial Guinea','GQ','240','GNQ','GEQ','XAF'),
('Greece','GR','30','GRC','GRE','EUR'),
('South Georgia And The South Sandwich Islands','GS','','SGS','','GBP'),
('Guatemala','GT','502','GTM','GUA','GTQ'),
('Guam','GU','+1 671','GUM','GUM','USD'),
('Guinea-bissau','GW','245','GNB','GBS','XOF'),
('Guyana','GY','592','GUY','GUY','GYD'),
('Hong Kong','HK','852','HKG','HKG','HKD'),
('Heard Island And McDonald Islands','HM','','HMD','','AUD'),
('Honduras','HN','504','HND','HON','HNL'),
('Croatia','HR','385','HRV','CRO','HRK'),
('Haiti','HT','509','HTI','HAI','HTG'),
('Hungary','HU','36','HUN','HUN','HUF'),
('Canary Islands','IC','','','','EUR'),
('Indonesia','ID','62','IDN','INA','IDR'),
('Ireland','IE','353','IRL','IRL','EUR'),
('Israel','IL','972','ISR','ISR','ILS'),
('Isle Of Man','IM','44','IMN','','GBP'),
('India','IN','91','IND','IND','INR'),
('British Indian','IO','246','IOT','','USD'),
('Iraq','IQ','964','IRQ','IRQ','IQD'),
('Iran','IR','98','IRN','IRI','IRR'),
('Iceland','IS','354','ISL','ISL','ISK'),
('Italy','IT','39','ITA','ITA','EUR'),
('Jersey','JE','44','JEY','JCI','GBP'),
('Jamaica','JM','+1 876','JAM','JAM','JMD'),
('Jordan','JO','962','JOR','JOR','JOD');