USE Currencies;

INSERT INTO Regions (region_alpha2) VALUES
('centralAsia'),
('southernAsia'),
('southeastAsia'),
('eastAsia'),
('westernAsia'),
('asia'),
('centralAfrica'),
('northAfrica'),
('southernAfrica'),
('eastAfrica'),
('westAfrica'),
('africa'),
('centralAmerica'),
('northernAmerica'),
('caribbean'),
('northAmerica'),
('southAmerica'),
('antartica'),
('northernEurope'),
('southernEurope'),
('easternEurope'),
('westernEurope'),
('europe'),
('eurozone'),
('australia'),
('melanesia'),
('micronesia'),
('polynesia'),
('oceania');