USE Currencies;

INSERT INTO Currencies (currency_name, alpha2,CallingCodes, alpha3, ioc, symbol) VALUES
('Japan','JP','81','JPN','JPN','JPY'),
('Kenya','KE','254','KEN','KEN','KES'),
('Kyrgyzstan','KG','996','KGZ','KGZ','KGS'),
('Cambodia','KH','855','KHM','CAM','KHR'),
('Kiribati','KI','686','KIR','KIR','AUD'),
('Comoros','KM','269','COM','COM','KMF'),
('Saint Kitts And Nevis','KN','+1 869','KNA','SKN','XCD'),
('Korea North','KP','850','PRK','PRK','KPW'),
('Korea South','KR','82','KOR','KOR','KRW'),
('Kuwait','KW','965','KWT','KUW','KWD'),
('Cayman Islands','KY','+1 345','CYM','CAY','KYD'),
('Kazakhstan','KZ','7','+7 6','+7 7','KAZ'),
('Lao Peoples Democratic Republic','LA','856','LAO','LAO','LAK'),
('Lebanon','LB','961','LBN','LIB','LBP'),
('Saint Lucia','LC','+1 758','LCA','LCA','XCD'),
('Liechtenstein','LI','423','LIE','LIE','CHF'),
('Sri Lanka','LK','94','LKA','SRI','LKR'),
('Liberia','LR','231','LBR','LBR','LRD'),
('Lesotho','LS','266','LSO','LES','LSL'),
('Lithuania','LT','370','LTU','LTU','EUR'),
('Luxembourg','LU','352','LUX','LUX','EUR'),
('Latvia','LV','371','LVA','LAT','EUR'),
('Libya','LY','218','LBY','LBA','LYD'),
('Morocco','MA','212','MAR','MAR','MAD'),
('Monaco','MC','377','MCO','MON','EUR'),
('Moldova','MD','373','MDA','MDA','MDL'),
('Montenegro','ME','382','MNE','MNE','EUR'),
('Saint Martin','MF','590','MAF','','EUR'),
('Madagascar','MG','261','MDG','MAD','MGA'),
('Marshall Islands','MH','692','MHL','MHL','USD'),
('Macedonia','MK','389','MKD','MKD','MKD'),
('Mali','ML','223','MLI','MLI','XOF'),
('Myanmar','MM','95','MMR','MYA','MMK'),
('Mongolia','MN','976','MNG','MGL','MNT'),
('Macao','MO','853','MAC','MAC','MOP'),
('Northern Mariana Islands','MP','+1 670','MNP','','USD'),
('Martinique','MQ','596','MTQ','','EUR'),
('Mauritania','MR','222','MRT','MTN','MRO'),
('Montserrat','MS','+1 664','MSR','','XCD'),
('Malta','MT','356','MLT','MLT','EUR'),
('Mauritius','MU','230','MUS','MRI','MUR'),
('Maldives','MV','960','MDV','MDV','MVR'),
('Malawi','MW','265','MWI','MAW','MWK'),
('Mexico','MX','52','MEX','MEX','MXN'),
('Malaysia','MY','60','MYS','MAS','MYR'),
('Mozambique','MZ','258','MOZ','MOZ','MZN'),
('Namibia','NA','264','NAM','NAM','NAD'),
('New Caledonia','NC','687','NCL','','XPF'),
('Niger','NE','227','NER','NIG','XOF'),
('Norfolk Island','NF','672','NFK','','AUD'),
('Nigeria','NG','234','NGA','NGR','NGN'),
('Nicaragua','NI','505','NIC','NCA','NIO'),
('Netherlands','NL','31','NLD','NED','EUR'),
('Norway','NO','47','NOR','NOR','NOK'),
('Nepal','NP','977','NPL','NEP','NPR'),
('Nauru','NR','674','NRU','NRU','AUD'),
('Niue','NU','683','NIU','','NZD'),
('New Zealand','NZ','64','NZL','NZL','NZD'),
('Oman','OM','968','OMN','OMA','OMR'),
('Panama','PA','507','PAN','PAN','PAB');